import { jsPDF } from 'jspdf';
import type { AIResult } from '../hooks/useAI';

export const generatePDFReport = (result: AIResult) => {
  const doc = new jsPDF();
  const date = new Date().toLocaleDateString();

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('CliniScan AI Diagnostic Report', 20, 25);
  
  doc.setFontSize(10);
  doc.text(`Report ID: #CLN-${Math.floor(1000 + Math.random() * 9000)}`, 160, 20);
  doc.text(`Date: ${date}`, 160, 27);

  // Patient Info Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text('Patient Information', 20, 55);
  doc.setLineWidth(0.5);
  doc.line(20, 58, 190, 58);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Name: Case Study #A-102', 20, 68);
  doc.text('Age / Gender: 45Y / Male', 80, 68);
  doc.text('Referral: General Radiology', 140, 68);

  // Diagnosis Summary
  doc.setFillColor(248, 250, 252);
  doc.rect(20, 75, 170, 40, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text('Diagnosis Summary:', 30, 85);
  doc.setFontSize(18);
  doc.setTextColor(37, 99, 235);
  doc.text(result.prediction, 30, 95);
  
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text(`AI Confidence Score: ${result.confidence}%`, 30, 105);
  doc.text(`Severity Level: ${result.severity}`, 120, 105);

  // AI Explanation
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text('AI Clinical Interpretation', 20, 130);
  doc.setLineWidth(0.2);
  doc.line(20, 133, 190, 133);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const splitExplanation = doc.splitTextToSize(result.explanation, 160);
  doc.text(splitExplanation, 25, 142);

  // Metrics Table
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Performance Metrics', 20, 180);
  
  let y = 190;
  result.metrics.forEach(m => {
    doc.setFont('helvetica', 'normal');
    doc.text(m.label, 25, y);
    doc.setFont('helvetica', 'bold');
    doc.text(`${m.value}%`, 160, y);
    y += 10;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const footerText = 'Disclaimer: This report is generated by an AI system and should be reviewed by a certified medical professional.';
  doc.text(footerText, 20, 280);
  doc.text('Generated by CliniScan AI v2.0 - All Rights Reserved', 140, 280);

  // Save the PDF
  try {
    doc.save(`CliniScan_Report_${result.prediction.replace(/\s+/g, '_')}.pdf`);
  } catch (error) {
    console.error("PDF Generation failed:", error);
    alert("Failed to generate PDF report. Please try again.");
  }
};
